### PR TITLE
Sort with collator

### LINKED ISSUE #2037: Search/Collation  limitations when using non-ASCII scripts, or extended Latin
Version: 2017-02-19b

When running a wiki in a language that uses extended Latin (eg French), or non-Latin scripts (eg Greek), the indexing (including collation) and search function has the following two limitations

1. Accented and not-accented versions of the same character are not treated as equivalent. For example "é" and "e" (French), or "έ" and "ε" are not treated as the same character for indexing and search purposes, even though that is the expected behaviour for speakers of those languages. 

2. In extended Latin, and non-ASCII alphabets, capital and lowercase letters are not treated as equivalent, while in basic ASCII they are. For example in Greek, the search function cannot find "Εντός" if search for "εντός" (Ε-ε are the upper/lowercase pair). 

Those two limitations in combination, also resort to collation being wrong, as dokuwiki collates all accented characters before non-accented ones.

For example, in Greek, dokuwiki gives:

> Άλφα
> Έψιλον
> Βήτα
> Γάμμα
> Δέλτα

and not the correct

> Άλφα
> Βήτα
> Γάμμα
> Δέλτα
> Έψιλον

Another report of the issue I found while looking for workarounds: https://forum.dokuwiki.org/thread/3892

### PR DESCRIPTION
**Pull request by moisesbr-dw**
When `intl` extension is available, all alphabetical sorts are done using a collator. Otherwise, primitive PHP functions are called.

The collator is created using the locale given in `$conf['lang']`. It always uses case insensitive "natural" ordering in its collation. The fallback solution uses the primitive PHP functions that return almost the same results when the input is text with only `[A-Za-z0-9]` characters.

All those screens will be properly sorted when `intl` extension is configured in `php.ini`:
- Sitemap (Index)
- Search
  - Matching pagenames
  - Fulltext results [added]
  - namespace selector below search field
- Quick search (when typing)
- Backlinks
- All media lists (including fullscreen)
  - Media backlinks (View tab in the 3rd column of Media Manager)
- Internal link suggestion when editing a page
- Administration
- Access Control List Management
  - tree list of namespaces and pages
  - drop-down list with users and groups
  - rule list by page/namespace (main sort)
  - rule list by user/group (secondary sort) [added]
- Authorization plugins
  - group sort in authplain [added]
- List of all pages in Remote API [added]
- OpenSearch suggestions
- Command line tool wantedpages.php

Future maintenance (e.g. plugins) will be very easy. Alphabetical comparisons and sorts should be changed the following way:
- from `strcmp()`, `strcasecmp()`, `strnatcmp()` and `strnatcasecmp()` to **`intl_strcmp()`**
- from `sort()` to **`intl_sort()`**
- from `ksort()` to **`intl_ksort()`**
- from `asort()`, `natsort()` and `natcasesort()` to **`intl_asort()`** or **`intl_asortFN()`**

Closes #2037 (collation part).

### CODE REVIEW

**Comment by moisesbr-dw** [comment]
Closes #2037 (collation part).

**Comment by moisesbr-dw** [comment]
Why

`php phpunit-7.5.20.phar tests\inc\sort_with_collator.test.php`

works (all tests pass) but 

`php phpunit-7.5.20.phar`

fails (method `setUp()` in `sort_with_collator.test.php` does not get called)?

**Comment by moisesbr-dw** [comment]
To really test this pull request, configure `lang` to a language where an accented letter is a letter by its own, that is, it is taken into account in the alphabetical order.

My tests used Esperanto: A B C Ĉ D E F G Ĝ H Ĥ I J Ĵ K L M N O P R S Ŝ T U Ŭ V Z

You may also use:
* Spanish: A B C D E F G H I J K L M N Ñ O P Q R S T U V W X Y Z
* Serbian: A B C Č Ć D Dž Đ E F G H I J K L Lj M N Nj O P R S Š T U V Z Ž
* Polish: A Ą B C Ć D E Ę F G H I J K L Ł M N Ń O Ó P Q R S Ś T U V W X Y Z Ź Ż
* Turkish: A B C Ç D E F G Ğ H I İ J K L M N O Ö P R S Ş T U Ü V Y Z
* languages with non-Latin scripts, like Russian, Greek, Japanese

**Comment by moisesbr-dw** [comment]
[Help wanted](https://forum.dokuwiki.org/d/17871-help-wanted-does-your-native-language-has-separate-letters-with-accents) for this pull request!

**Comment by lmachucab** [comment]
I just found out about this while looking for information on how to generate correct internationalized links to pages in Dokuwiki (eg.: ``doku.php/pages/Aragón`` instead of ``doku.php/pages/Arag%C3%B3n``, like what Wikipedia does). If any more specific tests are desired I am willing to give this a try during the next weekend, as well as report on aftereffects of upgrading a Dokuwiki installation running on a previous version to this fork.

Congrats @moisesbr-dw on testing with Esperanto btw, one of the cool languages out there.

**Comment by moisesbr-dw** [comment]
Hello @lmachucab ,

> I just found out about this while looking for information on how to generate correct internationalized links to pages in Dokuwiki (eg.: `doku.php/pages/Aragón` instead of `doku.php/pages/Arag%C3%B3n`, like what Wikipedia does). If any more specific tests are desired I am willing to give this a try during the next weekend, as well as report on aftereffects of upgrading a Dokuwiki installation running on a previous version to this fork.

Thank you very much, your help will be much appreciated.

> Congrats @moisesbr-dw on testing with Esperanto btw, one of the cool languages out there.

Mi gratas mian propran jukon. (I scratch my own itch.) :wink:

File: inc/sort.php [hunk 1]
```diff
@@ -0,0 +1,188 @@
...
+ * @param string $fn1 The first filename.
+ * @param string $fn2 The second filename.
+ * @return int Returns < 0 if $fn1 is less than $fn2; > 0 if $fn1 is greater than $fn2, and 0 if they are equal.
+ *
+ * @author Moisés Braga Ribeiro <moisesbr@gmail.com>
+ */
+function _sort_filenames_without_collator($fn1, $fn2)
+{
+    return strnatcasecmp(utf8_decodeFN($fn1), utf8_decodeFN($fn2));
+}
```
Comment (splitbrain) [inline inc/sort.php:188]: I would prefer to have these function wrapped into a namespaced class `\dokuwiki\Utf8\Sort` similar to the other UTF-8 classes we have. We could then call `Sort::ksort()` instead of `intl_sort()`

**Comment by moisesbr-dw** [comment]
> This looks good except for my one comment about wrapping it in a class. @moisesbr-dw can you change that? Or shall I do it?

Sorry @splitbrain , I'll be very busy in the next days.
I'm glad you've found the changes worth merging!

**Comment by moisesbr-dw** [comment]
> Can we change the tests in a way that they use a dataProvider or load different test data from files, so we can setup test in various languages?

Only function `test_intl_strcmp()` uses a dataProvider.
This could certainly be extended to the other tests.
Unfortunately I won't be able to change the tests as soon as I would want.

**Comment by moisesbr-dw** [comment]
@splitbrain All tests are passing. Just to be sure, I'll pass through all screens listed in [the first message](https://github.com/splitbrain/dokuwiki/pull/3115#issue-426195050) before considering the PR done.

**Comment by moisesbr-dw** [comment]
Now I consider the test classes fully functional, testing everything in the Esperanto, German, Portuguese and Spanish collators.
I've written extensive comments to guide anyone interested in testing a collator for another language.

I still have to verify the screens as I've mentioned before.
I hope I'll manage to do that on the weekend.

@splitbrain could you please check the German data in the tests (last commit)?

@lmachucab  could you please do the same with the Spanish data?

**Comment by moisesbr-dw** [comment]
Screens tested.
From my part, all set and done, @splitbrain !

**Comment by splitbrain** [comment]
Merged. Excellent work here! Thanks a lot!

**Comment by Klap-in** [comment]
Thanks for this work! 
Could you update the start post please? Then I could use that for documentation updates at other places.

**Comment by moisesbr-dw** [comment]
> Thanks for this work!
> Could you update the function names in the start post please? Then I could use that for documentation updates at other places.

Done!

**Comment by moisesbr-dw** [comment]
Maybe a `devel:sort` page could be inserted somewhere in the Development Manual.

**Comment by moisesbr-dw** [comment]
@Klap-in please take a look at the files attached in [this comment](https://github.com/splitbrain/dokuwiki/issues/2037#issuecomment-623194166), as they provide valuable information.

**Comment by lmachucab** [comment]
I'll try to get to this when I have some extra time. Haven't really touched anything DW-related in a few weeks.

**Comment by lmachucab** [comment]
I'll try to get to this when I have some extra time. Haven't really touched anything DW-related in a few weeks.
