### PR TITLE
RSS Feed: Disabling search fix + Code Style

### LINKED ISSUE #2727: feed.php bug
In search mode, if someone put large query utf-8 string, Server process may suffer time out.

like this.

> http://dokuwiki.example/feed.php?mode=search&q=미네이랑의_비극_을_예견한_듯한_브라질의_독일전_패배가_묘사_되어_팬들이_감탄하기도_하였다._해당_에피소드는_월드컵_전에_방송되었거늘..._물론_준결승이_아니라_결승에서_진_것임이_다르긴_하다._1315_영국미네이랑의_비극_을_예견한_듯한_브라질의_독일전_패배가_묘사_되어_팬들이_감탄하기도_하였다._해당_에피소드는_월드컵_전에_방송되었거늘..._물론_준결승이_아니라_결승에서_진_것임이_다르긴_하다._1315_영국미네이랑의_비극_을_예견한_듯한_브라질의_독일전_패배가_묘사_되어_팬들이_감탄하기도_하였다._해당_에피소드는_월드컵_전에_방송되었거늘..._물론_준결승이_아니라_결승에서_진_것임이_다르긴_하다._1315_영국

### PR DESCRIPTION
**Pull request by jpedryc**
Fixes #2727 

This is my first PR here, so I'm open for any criticism :stuck_out_tongue_closed_eyes: The majority of this PR are code style fixes run automatically by PHP Storm. Used [the coding style](https://www.dokuwiki.org/devel:coding_style) found in the wiki. One addition from my side - **changed `array()` to `[]`**. According to the least supported PHP version (5.6) everything should be fine.

### CODE REVIEW

File: feed.php [hunk 1]
```diff
@@ -509,9 +514,9 @@ function rssListNamespace($opt) {
  * @author Andreas Gohr <andi@splitbrain.org>
  */
 function rssSearch($opt) {
-    if(!$opt['search_query']) return array();
+    if(!$opt['search_query'] || !actionOK('search')) return [];
```
Comment (jpedryc) [inline feed.php:517]: Here is the actual change (fix) - we just return empty results when someone is trying to search whenever it's disabled.

**Comment by jpedryc** [comment]
I'll review the code style issues in the coming days :+1:

File: feed.php (hunk 1 above)
Comment (splitbrain) [reply feed.php]: Tip: next time separate the style adjustments and the functional change into two separate commits.
