### PR TITLE
Make router work with dotted page names. fixes #3165

### LINKED ISSUE #3165: PHP embedded webserver can't serve page with a dot in the name.
Hi,

Because PHP has a strange behaviour with requests that have a dot in the name, it cannot serve pages whose name has a dot.

How to reproduce. 

1.  `php -S 127.0.0.1:8000 index.php`
2. point your browser to http://localhost:8000/this.is.broken

### PR DESCRIPTION
**Pull request by splitbrain**
This should work around PHP bug #61286

Seems to work well but could use some additional manual testing.

### CODE REVIEW

File: index.php [hunk 1]
```diff
@@ -13,58 +13,63 @@
...
     } else {
         # static files
         return false;
     }
+} else {
+    // treat everything else as a potential wiki page
+    // working around https://bugs.php.net/bug.php?id=61286
+    if (isset($_SERVER['PATH_INFO'])) {
+        $_GET['id'] = $_SERVER['PATH_INFO'];
+    } else {
```
Comment (phy25) [inline index.php:70]: Regarding the discussion in https://github.com/splitbrain/dokuwiki/issues/3165#issuecomment-643070207, I would assume cli-server always has the root in DokuWiki root (because the previous `$_SERVER['SCRIPT_NAME'] !== '/index.php'` condition). Anyway it looks like the following patch works fine for `/`, `/index.php` (no argument set) and `/?id=index.php` (`index.php`), `index` (`index`).

```suggestion
    } elseif ($_SERVER['SCRIPT_NAME'] !== $_SERVER['PHP_SELF']) {
```

File: index.php [hunk 2]
```diff
@@ -13,58 +13,63 @@
...
-} else if(file_exists($_SERVER['DOCUMENT_ROOT'] . $_SERVER['SCRIPT_NAME'])) {
-    # existing files
-
-    # access limitiations
-    if(preg_match('/\/([\._]ht|README$|VERSION$|COPYING$)/', $_SERVER['SCRIPT_NAME']) or
+    // access limitiations
+    if (preg_match('/\/([._]ht|README$|VERSION$|COPYING$)/', $_SERVER['SCRIPT_NAME']) or
         preg_match('/^\/(data|conf|bin|inc)\//', $_SERVER['SCRIPT_NAME'])
     ) {
         die('Access denied');
```
Comment (phy25) [inline index.php:55]:
```suggestion
        header('HTTP/1.1 403 Forbidden');
        die('Access denied');
```

File: index.php (hunk 1 above)
Comment (schplurtz) [reply index.php:70]: Hum. I tried this. Unfortunately, with this, any page with a dot in the name result in :start being loaded.  For example `http://127.0.0.1:8000/truc:piquant.1.cmd` will serve :start. Other pages load ok.

Comment (phy25) [reply index.php:70]: @schplurtz Thanks for testing! Proposing something new below.

File: index.php [hunk 3]
```diff
@@ -13,58 +13,63 @@
...
         return false;
     }
+} else {
+    // treat everything else as a potential wiki page
+    // working around https://bugs.php.net/bug.php?id=61286
+    if (isset($_SERVER['PATH_INFO'])) {
+        $_GET['id'] = $_SERVER['PATH_INFO'];
+    } else {
+        $_GET['id'] = $_SERVER['SCRIPT_NAME'];
+    }
```
Comment (phy25) [inline index.php:72]:
```suggestion
    $request_path = preg_split('/\?/', $_SERVER['REQUEST_URI'], 2)[0];
    if (isset($_SERVER['PATH_INFO'])) {
        $_GET['id'] = $_SERVER['PATH_INFO'];
    } elseif (!($request_path == '/' || $request_path == '/index.php')) {
        $_GET['id'] = $_SERVER['SCRIPT_NAME'];
    }
```

Comment (schplurtz) [reply index.php:72]: All pages with dotted name and non dotted name can be loaded/edited with this one. `http://127.0.0.1/` gives the start page.

I just realize that userewrite is by nature an ambiguous notation. is `/index.php` a scriptname or a pagename ? And, with useslash=1, `/lib/exe/fetch.php` is a scriptname but `/lib/exe/schproutz.php` is a pagename. Funny.

Here, `/index.php` gives the startpage and `?id=index.php` gives the page called index.php. but that's normal.
